// HydroAgent design-system styles (HMI cyberpunk theme).
// Extracted verbatim from HydroAgent.jsx during the modular refactor.

const S = {
  surfaceLanding: {
    display:       "flex",
    flexDirection: "column",
    height:        "calc(100vh - 52px)",
    minHeight:     "560px",
    background:    "linear-gradient(135deg, #020C10 0%, #041820 55%, #020C10 100%)",
    position:      "relative",
    overflow:      "hidden",
    fontFamily:    "'IBM Plex Mono', monospace",
  },
  surfacePage: {
    display:       "flex",
    flexDirection: "column",
    height:        "calc(100vh - 52px)",
    fontFamily:    "'IBM Plex Mono', monospace",
    position:      "relative",
    zIndex:        1,
  },

  /* Header */
  header: {
    borderBottom: "1px solid rgba(0,245,255,0.10)",
    background:   "rgba(2,12,16,0.7)",
    padding:      "10px clamp(12px, 4vw, 28px)",
    flexShrink:   0,
  },
  headerInner: {
    maxWidth: "880px", margin: "0 auto",
    display: "flex", alignItems: "center", gap: "10px",
  },
  headerDot: {
    width: "6px", height: "6px", borderRadius: "50%",
    background: "#00FF88", boxShadow: "0 0 6px #00FF88",
    flexShrink: 0,
  },
  headerTitle: {
    fontFamily:    "'Orbitron', sans-serif",
    fontSize:      "12px",
    fontWeight:    700,
    color:         "#00F5FF",
    letterSpacing: "0.1em",
  },
  headerSub: {
    fontSize:      "9px",
    color:         "#2a5070",
    letterSpacing: "0.12em",
    marginLeft:    "8px",
  },
  headerActions: {
    marginLeft: "auto",
    display: "flex", gap: "8px", alignItems: "center",
  },
  smallBtn: {
    background: "transparent",
    border: "1px solid rgba(0,245,255,0.18)",
    borderRadius: "3px",
    padding: "4px 10px",
    color: "#4A7A8A",
    fontSize: "9px",
    fontFamily: "'IBM Plex Mono', monospace",
    letterSpacing: "0.1em",
    textTransform: "uppercase",
    cursor: "pointer",
    textDecoration: "none",
    transition: "all 0.2s",
  },

  /* Messages */
  msgArea: {
    flex:      1,
    overflowY: "auto",
    padding:   "20px clamp(12px, 4vw, 28px)",
  },
  msgInner: {
    maxWidth: "880px", margin: "0 auto",
    display: "flex", flexDirection: "column", gap: "16px",
  },

  bubble: (isUser) => ({
    maxWidth:     "760px",
    width:        "100%",
    margin:       isUser ? "0 0 0 auto" : "0",
    background:   isUser ? "rgba(0,245,255,0.06)" : "rgba(4,24,32,0.8)",
    border:       isUser ? "1px solid rgba(0,245,255,0.20)"
                         : "1px solid rgba(0,245,255,0.08)",
    borderRadius: "6px",
    padding:      "14px 18px",
    alignSelf:    isUser ? "flex-end" : "flex-start",
  }),
  bubbleLabel: {
    fontSize: "8px",
    letterSpacing: "0.14em",
    textTransform: "uppercase",
    color: "#2a5070",
    marginBottom: "6px",
  },
  bubbleText: {
    fontSize:   "13px",
    color:      "#c8e8f0",
    lineHeight: "1.75",
    wordBreak:  "break-word",
    fontFamily: "'Inter', sans-serif",
  },
  cursor: {
    color: "#00F5FF",
    display: "inline-block",
    verticalAlign: "baseline",
  },

  /* Empty state */
  empty: {
    maxWidth: "640px",
    margin:   "min(10vh, 80px) auto 24px",
    textAlign: "center",
    padding:   "0 12px",
  },
  emptyBadge: {
    display: "inline-flex", alignItems: "center", gap: "6px",
    border: "1px solid rgba(0,255,136,0.25)",
    borderRadius: "3px",
    padding: "4px 10px",
    marginBottom: "18px",
  },
  emptyDot: {
    width: "5px", height: "5px", borderRadius: "50%",
    background: "#00FF88", boxShadow: "0 0 6px #00FF88",
  },
  emptyBadgeText: {
    fontSize: "9px",
    color: "#00FF88",
    letterSpacing: "0.16em",
    textTransform: "uppercase",
    fontFamily: "'IBM Plex Mono', monospace",
  },
  welcomeLanding: {
    fontSize:   "clamp(20px, 3.4vw, 30px)",
    fontWeight: 600,
    color:      "#E8F8FF",
    lineHeight: 1.35,
    marginBottom: "26px",
    fontFamily: "'Inter', sans-serif",
    letterSpacing: "-0.01em",
  },
  welcomePage: {
    fontSize:   "clamp(16px, 2vw, 20px)",
    fontWeight: 500,
    color:      "#E8F8FF",
    lineHeight: 1.5,
    marginBottom: "20px",
    fontFamily: "'Inter', sans-serif",
  },
  suggestLabel: {
    fontSize: "9px",
    letterSpacing: "0.18em",
    textTransform: "uppercase",
    color: "#2a5070",
    marginBottom: "10px",
    fontFamily: "'IBM Plex Mono', monospace",
  },
  chipsWrap: {
    display: "flex", flexWrap: "wrap", gap: "8px",
    justifyContent: "center",
  },
  chip: {
    background: "rgba(4,24,32,0.7)",
    border: "1px solid rgba(0,245,255,0.18)",
    borderRadius: "999px",
    padding: "8px 14px",
    color: "#7ab8c8",
    fontSize: "12px",
    fontFamily: "'Inter', sans-serif",
    letterSpacing: "0.01em",
    cursor: "pointer",
    transition: "all 0.18s",
    textAlign: "left",
    lineHeight: 1.3,
    maxWidth: "320px",
  },

  /* Input */
  inputArea: {
    borderTop:  "1px solid rgba(0,245,255,0.10)",
    background: "rgba(2,12,16,0.85)",
    padding:    "12px clamp(12px, 4vw, 28px) 10px",
    flexShrink: 0,
  },
  inputInner: {
    maxWidth:     "880px",
    margin:       "0 auto",
    display:      "flex",
    alignItems:   "flex-end",
    gap:          "10px",
    background:   "rgba(4,24,32,0.9)",
    border:       "1px solid rgba(0,245,255,0.14)",
    borderRadius: "6px",
    padding:      "10px 14px",
  },
  prompt: {
    fontSize: "14px",
    color: "#00F5FF",
    flexShrink: 0,
    paddingBottom: "2px",
  },
  textarea: {
    flex: 1,
    background: "transparent",
    border: "none",
    outline: "none",
    color: "#E8F8FF",
    fontSize: "14px",
    lineHeight: "1.6",
    resize: "none",
    maxHeight: "140px",
    overflowY: "auto",
    fontFamily: "'Inter', sans-serif",
  },
  btn: {
    flexShrink: 0,
    padding: "5px 14px",
    borderRadius: "3px",
    fontSize: "9px",
    letterSpacing: "0.10em",
    fontFamily: "'IBM Plex Mono', monospace",
    fontWeight: 600,
    cursor: "pointer",
    border: "none",
    textTransform: "uppercase",
    transition: "all 0.15s",
  },
  btnActive: {
    background: "#00F5FF",
    color: "#020C10",
  },
  btnDisabled: {
    background: "rgba(0,245,255,0.06)",
    color: "#2a5070",
    cursor: "not-allowed",
  },
  btnStop: {
    background: "rgba(255,80,80,0.15)",
    color: "#ff6060",
    border: "1px solid rgba(255,80,80,0.25)",
  },
  hint: {
    maxWidth: "880px",
    margin: "6px auto 0",
    fontSize: "8px",
    color: "#1e3050",
    letterSpacing: "0.06em",
    textAlign: "right",
    fontFamily: "'IBM Plex Mono', monospace",
  },

  /* Phase Resume */
  phaseResume: {
    maxWidth: "640px",
    margin: "min(10vh, 80px) auto 24px",
    textAlign: "center",
    padding: "0 12px",
  },
  phaseResumeBadge: {
    display: "inline-flex", alignItems: "center", gap: "6px",
    border: "1px solid rgba(255,180,0,0.35)",
    borderRadius: "3px",
    padding: "4px 10px",
    marginBottom: "18px",
  },
  phaseResumeDot: {
    width: "5px", height: "5px", borderRadius: "50%",
    background: "#FFB400", boxShadow: "0 0 6px #FFB400",
  },
  phaseResumeBadgeText: {
    fontSize: "9px",
    color: "#FFB400",
    letterSpacing: "0.16em",
    textTransform: "uppercase",
    fontFamily: "'IBM Plex Mono', monospace",
  },
  phaseResumeTitle: {
    fontSize: "clamp(18px, 2.5vw, 24px)",
    fontWeight: 600,
    color: "#E8F8FF",
    marginBottom: "12px",
    fontFamily: "'Inter', sans-serif",
  },
  phaseResumeText: {
    fontSize: "13px",
    color: "#8ab8c8",
    lineHeight: 1.6,
    marginBottom: "20px",
    fontFamily: "'Inter', sans-serif",
  },
  phaseResumeActions: {
    display: "flex",
    gap: "10px",
    justifyContent: "center",
    flexWrap: "wrap",
  },
  phaseResumeBtn: {
    padding: "8px 16px",
    borderRadius: "3px",
    fontSize: "12px",
    fontFamily: "'IBM Plex Mono', monospace",
    fontWeight: 600,
    cursor: "pointer",
    border: "1px solid",
    textTransform: "uppercase",
    letterSpacing: "0.08em",
    transition: "all 0.15s",
  },
  phaseResumeBtnContinue: {
    background: "rgba(0,245,255,0.12)",
    color: "#00F5FF",
    borderColor: "rgba(0,245,255,0.25)",
  },
  phaseResumeBtnReset: {
    background: "transparent",
    color: "#2a5070",
    borderColor: "rgba(0,245,255,0.12)",
  },
};

export { S };
